version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: game-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gamedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: